# Generated by Django 3.2.2 on 2021-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
