# Generated by Django 3.2.2 on 2021-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211004_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_unemployed',
            field=models.BooleanField(default=True, verbose_name='unemployed'),
            preserve_default=False,
        ),
    ]
