# Generated by Django 3.2.2 on 2021-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nysc_not_applicable_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
