# Generated by Django 3.2.2 on 2021-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_has_added_employment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_unemployed',
            field=models.BooleanField(blank=True, null=True, verbose_name='unemployed'),
        ),
    ]
