# Generated by Django 3.2.2 on 2021-10-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_unemployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
