# Generated by Django 3.2.2 on 2021-10-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211011_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_unemployed',
        ),
        migrations.AddField(
            model_name='user',
            name='completed_nysc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_work_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='work experience'),
        ),
        migrations.AddField(
            model_name='user',
            name='nysc_not_applicable_reason',
            field=models.TextField(null=True),
        ),
    ]
