# Generated by Django 3.2.2 on 2021-10-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211011_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_added_academic_detail',
            field=models.BooleanField(default=False),
        ),
    ]
