# Generated by Django 3.2.2 on 2021-10-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_has_added_academic_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_added_laptop_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_added_training_pathway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='take_laptop_loan',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
