# Generated by Django 3.2.2 on 2021-12-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211125_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremploymentdetail',
            name='currently_works_there',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
