# Generated by Django 3.2.2 on 2021-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211006_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremploymentdetail',
            name='enddate',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
