# Generated by Django 3.2.2 on 2021-12-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_useremploymentdetail_currently_works_there'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='volunter_year',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
