# Generated by Django 3.2.2 on 2021-10-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_useremploymentdetail_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremploymentdetail',
            name='is_actvie',
            field=models.BooleanField(default=True),
        ),
    ]
