# Generated by Django 3.2.2 on 2021-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useremploymentdetail_is_actvie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='local_gov',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='nearest_bustop',
            new_name='region',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_num',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.AddField(
            model_name='address',
            name='additional_info',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
