# Generated by Django 3.2.2 on 2021-12-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211227_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='tertiaryinstitution',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tertiaryinstitution',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
