# Generated by Django 3.2.2 on 2021-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211227_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
