# Generated by Django 3.2.2 on 2021-10-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_highschool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=300)),
                ('cohort', models.CharField(max_length=300)),
                ('campus', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pathway', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
