# Generated by Django 3.2.2 on 2021-10-20 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_trainingpathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_of_residence', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=300)),
                ('local_gov', models.CharField(max_length=300)),
                ('doc_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kyc_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
