# Generated by Django 3.2.2 on 2022-01-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220117_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpathway',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cohort'),
        ),
        migrations.AddField(
            model_name='trainingpathway',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
